### PR TITLE
iOS 10 crash fix

### PR DESCRIPTION
**Pull request by monzy613**
however maybe the time calling setPrefetchingEnabled is not good @jamztang

### CODE REVIEW

**Comment by Raesu** [comment]
I have a nasty crash in a `UICollectionView` I'm using with this layout. It seems to only be an issue when I'm using 2 sections. I think it could be an issue with prefetching. I'd like to test this but can't figure out how to update my podfile to do so. Any assistance on how to point to this commit?

**Comment by chrene** [comment]
You don't need to let your collection view rely on the layout disabling prefetching on your collection view. You can do that in viewDidLoad or a similar place.

**Comment by Raesu** [comment]
Oh, awesome. That one line fixed it! Seems odd it was only an issue with my `UICollectionView` that uses 2 sections, and not the one with 1 section. Thank you @chrene !

**Comment by chrene** [comment]
Closing this since you can disable prefetching on the collection view in viewDidLoad instead of forcing it on the layout. We need another solution.

**Comment by monzy613** [comment]
@chrene the problem is, user's may not remember to call it in viewdidload.. so I'm not very sure where to call this method, thus I call it in prepareLayout (yes, not good, called time by time). Any suggestions

**Comment by monzy613** [comment]
@Raesu in terminal and cd in the folder where the Podfile exists : pod update CSStickyHeaderFlowLayout

**Pull request closed without merging**
