### PR TITLE
Allows to disable stretching view to more than set height.

### PR DESCRIPTION
**Pull request by Luzo**
For me header was always stretching to more than set size which was not desired behaviour. So I added option to disable this.

Thank you for possible merge.

### CODE REVIEW

**Comment by yoshiboarder** [comment]
Hi I think It still stretching the header view..

if let layout = self.collectionViewLayout as? CSStickyHeaderFlowLayout {
            layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 215)

            layout.parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.size.width, 215)
//            layout.itemSize = CGSizeMake(self.view.frame.size.width, 40)
            layout.parallaxHeaderAlwaysOnTop = false
            layout.disableStickyHeaders = true
        }


Could you advising me how to use that?

**Comment by Luzo** [comment]
Hi, you just have to set disableStretching property on layout to true. I am not sure, but setting item size might be necessary. 

Hope that it helps.

**Comment by yoshiboarder** [comment]
Thanks for the reply

I want implement like an spotify example(CSsticky example 1)

As you can see it seems not the stretch

Do you mean your commit set this feature right?




나의 iPhone에서 보냄

Aug 16, 2016 9:11 PM Luzo <notifications@github.com> 작성:

**Comment by Luzo** [comment]
If you want no overstretching then yes. If stretching over the maximum size is not your problem, then it will not help you. In the second scenario I suggest you to run the project, it contains samples .Probably you will find there wished behaviour.

**Comment by yoshiboarder** [comment]
Hi Thanks for the reply.

I understand…your code is not stretched.

here is my code..


I had already set the like this.. layout.disablestretching = true

if let layout = self.collectionViewLayout as? CSStickyHeaderFlowLayout {
            layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 215)

            layout.parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.size.width, 215)
            layout.parallaxHeaderAlwaysOnTop = false
            layout.disableStretching = true
        }


Um..My problem is… when I trying to scroll down then… parallaxHeader is not moved….yes it is not stretched..really great.

But Is it possible If I scroll down then…parallaxHeader also move down…following the UICollectionView’s section header top


like this example..




Thank you so much

**Comment by Luzo** [comment]
I am not sure what do you mean with it should move down. Like you want it to expand?

**Comment by yoshiboarder** [comment]
Can I send gif images to you via email? I means parallax header's top is not detached the navigation bar's bottom. But I want fix the parallax header's height and detach from navigationbars. Sorry for not clear my questions.

**Comment by jamztang** [comment]
Hi @Luzo, I've migrate the project to under an organization, hopefully to let the community to be happy to be part of the owner of this library. Please forgive my lack of time to continue maintain the library, allow me to add you as a contributor, so we can move things forward.

**Pull request merged**
